baseline_idx: 0
files:
- ./experiments/loop-unroll/profilings/test-no-unroll/n.txt
- ./experiments/loop-unroll/profilings/test-auto-unroll/n.txt
- ./experiments/loop-unroll/profilings/test-n-unroll/n.txt
- ./experiments/loop-unroll/profilings/test-no-unroll/r.txt
- ./experiments/loop-unroll/profilings/test-auto-unroll/r.txt
- ./experiments/loop-unroll/profilings/test-n-unroll/r.txt
- ./experiments/loop-unroll/profilings/test-no-unroll/t.txt
- ./experiments/loop-unroll/profilings/test-auto-unroll/t.txt
- ./experiments/loop-unroll/profilings/test-n-unroll/t.txt
- ./experiments/loop-unroll/profilings/test-no-unroll/rt.txt
- ./experiments/loop-unroll/profilings/test-auto-unroll/rt.txt
- ./experiments/loop-unroll/profilings/test-n-unroll/rt.txt
names_method:
- Naive (No Unroll)
- Naive (Auto Unroll)
- Naive (N Unroll)
- Rsqrt (No Unroll)
- Rsqrt (Auto Unroll)
- Rsqrt (N Unroll)
- ThirdLaw (No Unroll)
- ThirdLaw (Auto Unroll)
- ThirdLaw (N Unroll)
- Rsqrt+Third (No Unroll)
- Rsqrt+Third (Auto Unroll)
- Rsqrt+Third (N Unroll)
runs: 5
save-path: ./plots/loop-unroll/
