baseline_idx: 0
files:
- ./experiments/rsqrt-impact/profilings/test-rsqrt/n_1.txt
- ./experiments/rsqrt-impact/profilings/test-rsqrt/r_1.txt
- ./experiments/rsqrt-impact/profilings/test-rsqrt/r_2.txt
- ./experiments/rsqrt-impact/profilings/test-rsqrt/r_3.txt
- ./experiments/rsqrt-impact/profilings/test-rsqrt/rt_1.txt
- ./experiments/rsqrt-impact/profilings/test-rsqrt/rt_2.txt
- ./experiments/rsqrt-impact/profilings/test-rsqrt/rt_3.txt
names_method:
- Naive (1/sqrt)
- Rsqrt (1 iter)
- Rsqrt (2 iter)
- Rsqrt (3 iter)
- Rsqrt+Third (1 iter)
- Rsqrt+Third (2 iter)
- Rsqrt+Third (3 iter)
runs: 5
save-path: ./plots/rsqrt-impact/
