files:
  - "./experiments/kernel/profilings/n.txt"
  - "./experiments/kernel/profilings/b_256.txt"
  - "./experiments/kernel/profilings/bt_256.txt"
  - "./experiments/kernel/profilings/br_256.txt"
  - "./experiments/kernel/profilings/brt_256.txt"

names_method:
  - "Naive"
  - "Blocks"
  - "Blocks+Third"
  - "Blocks+Rsqrt"
  - "Blocks+Rsqrt+Third"

baseline_idx: 0
runs: 5
save-path: "./reports/serial/blocks/"
