files:
  - "./experiments/kernel/profilings/ba.txt"
  - "./experiments/kernel/profilings/n.txt"
  - "./experiments/kernel/profilings/t.txt"
  - "./experiments/kernel/profilings/r.txt"
  - "./experiments/kernel/profilings/b.txt"
  - "./experiments/kernel/profilings/rt.txt"
  - "./experiments/kernel/profilings/bt.txt"
  - "./experiments/kernel/profilings/br.txt"
  - "./experiments/kernel/profilings/brt.txt"

names_method:
  - "Baseline"
  - "Naive"
  - "ThirdLaw"
  - "Rsqrt"
  - "Blocks"
  - "Rsqrt+Third"
  - "Blocks+Third"
  - "Blocks+Rsqrt"
  - "Blocks+Rsqrt+Third"

baseline_idx: 0
runs: 5
save-path: "./reports/serial/kernel/"
