files:
  - "./experiments/omp/profilings/w_1_quiet.txt"
  - "./experiments/omp/profilings/w_2_quiet.txt"
  - "./experiments/omp/profilings/w_4_quiet.txt"
  - "./experiments/omp/profilings/w_8_quiet.txt"
  - "./experiments/omp/profilings/w_16_quiet.txt"
  - "./experiments/omp/profilings/w_32_quiet.txt"
  - "./experiments/omp/profilings/w_64_quiet.txt"

names_method:
  - "1 Thread"
  - "2 Threads"
  - "4 Threads"
  - "8 Threads"
  - "16 Threads"
  - "32 Threads"
  - "64 Threads"

baseline_idx: 0
runs: 1
save-path: "./reports/scaling/omp-weak-quiet/"
is_strong: false
is_weak: true
