"files": [
          "./src/profilings/test-serial/n.txt",
          "./src/profilings/test-serial/t.txt",
          "./src/profilings/test-serial/r.txt",
          "./src/profilings/test-serial/b.txt",
          "./src/profilings/test-serial/rt.txt",
          "./src/profilings/test-serial/bt.txt",
          "./src/profilings/test-serial/br.txt",
          "./src/profilings/test-serial/brt.txt"
]
"names_info": [
#          "Total Step",
#          "First Drift",
          "Compute Force",
#          "Kick",
#          "Second Drift"
]
"names_method": [
          "Naive",
          "ThirdLaw",
          "Rsqrt",
          "Blocks",
          "Rsqrt+ThirdLaw",
          "Blocks+ThirdLaw",
          "Blocks+Rsqrt",
          "Blocks+Rsqrt+ThirdLaw"
]

"runs": 5
"save-path": "./plots/test-serial/"
