"files": [
          "./src/profilings/test-serial-2/n.txt",
          "./src/profilings/test-serial-2/t.txt",
          "./src/profilings/test-serial-2/r.txt",
          "./src/profilings/test-serial-2/b.txt",
          "./src/profilings/test-serial-2/rt.txt",
          "./src/profilings/test-serial-2/bt.txt",
          "./src/profilings/test-serial-2/br.txt",
          "./src/profilings/test-serial-2/brt.txt"
]
"names_info": [
#          "Total Step",
#          "First Drift",
          "Compute Force",
#          "Kick",
#          "Second Drift"
]
"names_method": [
          "Naive",
          "ThirdLaw",
          "Rsqrt",
          "Blocks",
          "Rsqrt+ThirdLaw",
          "Blocks+ThirdLaw",
          "Blocks+Rsqrt",
          "Blocks+Rsqrt+ThirdLaw"
]

"runs": 5
"save-path": "./plots/test-serial/"
